### ISSUE TITLE
Trips Image Build Error - cannot find module for path crypto/ed25519**

### ISSUE THREAD

**Issue by grantjo78** [Microsoft-OpenHack/containers_artifacts#5]
Image build failing with below error.
build app: cannot find module for path crypto/ed25519

Rolling back to previous branch resolves issues

=> [internal] load build definition from Dockerfile_4                                                                                          0.0s
 => => transferring dockerfile: 39B                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 34B                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/alpine:3.10                                                                                  1.3s
 => [internal] load metadata for docker.io/library/golang:1.11.1                                                                                1.3s
 => [gobuild 1/5] FROM docker.io/library/golang:1.11.1@sha256:63ec0e29aeba39c0fe2fc6551c9ca7fa16ddf95394d77ccee75bc7062526a96c                  0.0s
 => CACHED [gorun 1/5] FROM docker.io/library/alpine:3.10@sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98               0.0s
 => [internal] load build context                                                                                                               0.0s
 => => transferring context: 18.15kB                                                                                                            0.0s
 => CACHED [gobuild 2/5] WORKDIR /go/src/app                                                                                                    0.0s
 => [gorun 2/5] RUN apk --no-cache add   curl   ca-certificates   jq   less   vim                                                               5.2s
 => [gobuild 3/5] COPY . .                                                                                                                      0.0s
 => ERROR [gobuild 4/5] RUN go get                                                                                                             30.0s
 => [gorun 3/5] WORKDIR /app                                                                                                                    0.0s
------                                                                                                                                               
 > [gobuild 4/5] RUN go get:                                                                                                                         
#12 0.147 go: finding github.com/gorilla/mux v1.6.2                                                                                                  
#12 0.149 go: finding github.com/prometheus/common v0.6.0                                                                                            
#12 0.149 go: finding github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe                                                                 
#12 0.153 go: finding github.com/codemodus/swagui v0.1.0                                                                                             
#12 0.155 go: finding github.com/golang/protobuf v1.3.2                                                                                              
#12 0.157 go: finding github.com/Azure/go-autorest/logger v0.2.1                                                                                     
#12 0.162 go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90                                                          
#12 0.165 go: finding github.com/Azure/go-autorest/autorest/date v0.3.0                                                                              
#12 0.165 go: finding github.com/Azure/go-autorest/tracing v0.6.0
#12 0.695 go: finding golang.org/x/sys v0.0.0-20190801041406-cbf593c0f2f3
#12 1.978 go: finding github.com/pmezard/go-difflib v1.0.0
#12 2.111 go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
#12 2.132 go: finding github.com/gorilla/context v1.1.1
#12 2.387 go: finding golang.org/x/crypto v0.0.0-20201002170205-7f63de1d35b0
#12 2.661 go: finding github.com/go-logfmt/logfmt v0.4.0
#12 2.744 go: finding github.com/sirupsen/logrus v1.2.0
#12 3.845 go: finding github.com/prometheus/client_golang v1.1.0
#12 4.364 go: finding github.com/julienschmidt/httprouter v1.2.0
#12 4.778 go: finding github.com/denisenkom/go-mssqldb v0.10.0
#12 4.783 go: finding github.com/golang/protobuf v1.3.1
#12 4.792 go: finding github.com/pkg/errors v0.8.0
#12 4.793 go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
#12 5.355 go: finding github.com/beorn7/perks v1.0.1
#12 5.392 go: finding github.com/Azure/go-autorest v14.2.0+incompatible
#12 5.992 go: finding github.com/golang/protobuf v1.2.0
#12 6.786 go: finding github.com/stretchr/testify v1.3.0
#12 6.853 go: finding github.com/davecgh/go-spew v1.1.1
#12 7.123 go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
#12 7.743 go: finding github.com/stretchr/testify v1.2.2
#12 7.743 go: finding github.com/stretchr/objx v0.1.1
#12 7.837 go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
#12 7.840 go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
#12 7.863 go: finding github.com/prometheus/procfs v0.0.3
#12 8.845 go: finding github.com/prometheus/client_golang v1.0.0
#12 9.006 go: finding golang.org/x/net v0.0.0-20190613194153-d28f0bde5980
#12 9.832 go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
#12 9.979 go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
#12 10.15 go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
#12 10.30 go: finding github.com/stretchr/objx v0.1.0
#12 10.80 go: finding gopkg.in/yaml.v2 v2.2.1
#12 10.89 go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
#12 10.89 go: finding github.com/prometheus/common v0.4.1
#12 10.89 go: finding github.com/golang-jwt/jwt/v4 v4.0.0
#12 10.90 go: finding github.com/modern-go/reflect2 v1.0.1
#12 11.48 go: finding github.com/google/go-cmp v0.3.0
#12 11.54 go: finding github.com/json-iterator/go v1.1.6
#12 12.14 go: finding golang.org/x/crypto v0.0.0-20190325154230-a5d413f7728c
#12 12.15 go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
#12 12.73 go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
#12 12.74 go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
#12 13.38 go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
#12 13.56 go: finding github.com/go-logfmt/logfmt v0.3.0
#12 14.03 go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
#12 14.03 go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
#12 14.03 go: finding github.com/beorn7/perks v1.0.0
#12 14.04 go: finding github.com/go-stack/stack v1.8.0
#12 14.40 go: finding github.com/Azure/go-autorest/autorest/adal v0.9.15
#12 14.59 go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
#12 14.59 go: finding github.com/prometheus/client_golang v0.9.1
#12 14.72 go: finding github.com/json-iterator/go v1.1.7
#12 15.15 go: finding github.com/prometheus/procfs v0.0.2
#12 15.18 go: finding github.com/go-kit/kit v0.8.0
#12 15.72 go: finding github.com/Azure/go-autorest/autorest/mocks v0.4.1
#12 15.75 go: finding github.com/gogo/protobuf v1.1.1
#12 15.78 go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
#12 15.78 go: finding golang.org/x/sys v0.0.0-20181116152217-5ac8a444bdc5
#12 15.78 go: finding github.com/davecgh/go-spew v1.1.0
#12 15.79 go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
#12 15.89 go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
#12 15.93 go: finding golang.org/x/text v0.3.0
#12 15.94 go: finding github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
#12 16.06 go: finding github.com/google/gofuzz v1.0.0
#12 16.96 go: finding github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
#12 17.02 go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
#12 20.33 go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
#12 29.36 go: downloading github.com/denisenkom/go-mssqldb v0.10.0
#12 29.37 go: downloading github.com/gorilla/mux v1.6.2
#12 29.37 go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
#12 29.37 go: downloading github.com/codemodus/swagui v0.1.0
#12 29.37 go: downloading github.com/stretchr/testify v1.3.0
#12 29.38 go: downloading github.com/prometheus/client_golang v1.1.0
#12 29.41 go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.15
#12 29.43 go: downloading github.com/Azure/go-autorest/tracing v0.6.0
#12 29.44 go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
#12 29.44 go: downloading github.com/Azure/go-autorest/logger v0.2.1
#12 29.44 go: downloading golang.org/x/crypto v0.0.0-20201002170205-7f63de1d35b0
#12 29.44 go: downloading github.com/golang-jwt/jwt/v4 v4.0.0
#12 29.45 go: downloading github.com/golang/protobuf v1.3.2
#12 29.45 go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
#12 29.46 go: downloading github.com/prometheus/procfs v0.0.3
#12 29.47 go: downloading github.com/davecgh/go-spew v1.1.1
#12 29.49 go: downloading github.com/pmezard/go-difflib v1.0.0
#12 29.52 go: downloading github.com/beorn7/perks v1.0.1
#12 29.55 go: downloading github.com/prometheus/common v0.6.0
#12 29.61 go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
#12 29.64 go: downloading github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe
#12 29.91 build app: cannot find module for path crypto/ed25519

**Comment by Joll59** [comment]
Thanks for addressing this.
